version: '3.1'

services:
  postgres:
    container_name: postgres-market
    image: 'postgres:14-alpine'
    env_file:
      - ./.env.server
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
